title: Adrian Jarret
description: PhD Student in Signal Processing at EPFL.
author: "Adrian Jarret"
email: adrian.jarret@epfl.ch

theme: minima

# base_url: /gh-pages-minima-starter

# Minima social links
# twitter_username: xurxosanz
github_username: AdriaJ
# linkedin_username: jsanz
# rss: rss

social_links:
 - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=WXJAMi0AAAAJ" }

# Minima: show excerpts in the frontpage
# show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  # - _pages/about.md
  - _pages/talks.md
  - _pages/pubs.md
  # - _pages/archive.md

include:
    - _pages

exclude:
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
